name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.12.0'
          cache: 'npm'

      # Step 3: Change directory to static_server
      - name: Change directory to static_server
        run: cd static_server

      # Step 4: Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # Step 5: Build the project (if needed)
      - name: Build project
        run: npm run build  # Update this if you have a specific build command
      

      # Step 5: Configure Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 6: Upload dist folder as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
